### PR TITLE
change the clause condition to equal to 0 instead null

### PR DESCRIPTION
**Pull request by td928**

### CODE REVIEW

**Review by SPTKL — APPROVED** [review]
right we are not supposed to have job_inactive=NULL

**Review by mgraber — COMMENTED** [review]
@SPTKL In DevDB? When did that change?

**Comment by mgraber** [comment]
The phasing should already be resolved by https://github.com/NYCPlanning/db-knownprojects/pull/354. Is this addressing a new issue?

**Comment by td928** [comment]
> #354

Hey @mgraber  Then we will still need to make this change in order to fill the phasing assumption in kpdb for devdb no?

**Pull request closed without merging**
