### PR TITLE
adding units_gross as a second option to get units_net values populated

### PR DESCRIPTION
**Pull request by AmandaDoyle**
#395

### CODE REVIEW

**Comment by mbh329** [comment]
New output successfully populates these records with the `units_net`
Screenshot 2023-03-23 at 12 30 59 PM

**Comment by mbh329** [comment]
Hold off on merging, I spoke with sam and there is another issue:

DOB records that are active (status 1,2,3)  should have values in `within_5_years` = `units_net` * prop_within_5_years`

**Comment by AmandaDoyle** [comment]
@mbh329 added logic to address issue #397

**Comment by mbh329** [comment]
It totally could have been, just wanted to make you aware

**Comment by mbh329** [comment]
LGTM.
Screenshot 2023-03-23 at 2 54 36 PM

**Pull request merged**
